import { addDays, format } from "date-fns";

import { TTransportation } from "@/types/global";

function generateRandomDateTimeWithinWeek() {
	// Get a random number of days within the next week (including today)
	const randomDays = Math.floor(Math.random() * 7);

	// Get the date for the random day
	const randomDate = addDays(new Date(), randomDays);

	// Generate random times for pickup and dropoff
	const randomHour = Math.floor(Math.random() * 24);
	const randomMinute = Math.floor(Math.random() * 60);

	// Format the date, hour, and minute into ISO 8601 format
	const pickupTime = format(
		new Date(
			randomDate.getFullYear(),
			randomDate.getMonth(),
			randomDate.getDate(),
			randomHour,
			randomMinute,
		),
		"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
	);

	// For dropoff, add a random duration between 1 and 6 hours
	const dropoffHour = randomHour + Math.floor(Math.random() * 6) + 1;
	const dropoffMinute = Math.floor(Math.random() * 60);

	const dropoffTime = format(
		new Date(
			randomDate.getFullYear(),
			randomDate.getMonth(),
			randomDate.getDate(),
			dropoffHour,
			dropoffMinute,
		),
		"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
	);

	return { pickupTime, dropoffTime };
}

const pickUpTimesPairs = Array.from({ length: 25 }, (_, i) =>
	generateRandomDateTimeWithinWeek(),
);

let i = 0;
export const hardCodedTransportations: TTransportation[] = [
	{
		_id: "1",
		name: "Express Bus 101",
		type: "Bus",
		price: 25,
		availability: 0,
		pickUpLocation: "Downtown",
		dropOffLocation: "Airport",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "2",
		name: "City Taxi",
		type: "Car",
		price: 50,
		availability: 0,
		pickUpLocation: "Hotel Plaza",
		dropOffLocation: "Beach Resort",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "3",
		name: "Fast Express Train",
		type: "Train",
		price: 75,
		availability: 0,
		pickUpLocation: "Central Station",
		dropOffLocation: "City Terminal",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "4",
		name: "Morning Flight A201",
		type: "Plane",
		price: 200,
		availability: 0,
		pickUpLocation: "International Airport",
		dropOffLocation: "Capital City",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "5",
		name: "Ocean Cruiser",
		type: "Boat",
		price: 150,
		availability: 0,
		pickUpLocation: "Harbor Dock 5",
		dropOffLocation: "Island Resort",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "6",
		name: "Sunrise Bus 202",
		type: "Bus",
		price: 30,
		availability: 0,
		pickUpLocation: "Main Square",
		dropOffLocation: "Museum District",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "7",
		name: "Luxury Sedan",
		type: "Car",
		price: 80,
		availability: 0,
		pickUpLocation: "City Center",
		dropOffLocation: "Mountain Lodge",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "8",
		name: "Metro Rail Express",
		type: "Train",
		price: 60,
		availability: 0,
		pickUpLocation: "Metro Central",
		dropOffLocation: "Suburb Station",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "9",
		name: "AirJet 501",
		type: "Plane",
		price: 300,
		availability: 0,
		pickUpLocation: "Skyline Airport",
		dropOffLocation: "Tropical Beach",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "10",
		name: "Island Ferry",
		type: "Boat",
		price: 120,
		availability: 0,
		pickUpLocation: "Dock 1",
		dropOffLocation: "Island Cove",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "11",
		name: "Morning Shuttle",
		type: "Bus",
		price: 20,
		availability: 0,
		pickUpLocation: "Central Plaza",
		dropOffLocation: "Science Museum",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "12",
		name: "Premium Limo",
		type: "Car",
		price: 150,
		availability: 0,
		pickUpLocation: "Luxury Hotel",
		dropOffLocation: "City Hall",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "13",
		name: "Regional Express",
		type: "Train",
		price: 85,
		availability: 0,
		pickUpLocation: "City Main Station",
		dropOffLocation: "Countryside Terminal",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "14",
		name: "SkyLiner A350",
		type: "Plane",
		price: 250,
		availability: 0,
		pickUpLocation: "International Hub",
		dropOffLocation: "Coastal Airport",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "15",
		name: "Sunset Sail",
		type: "Boat",
		price: 180,
		availability: 0,
		pickUpLocation: "Marina Bay",
		dropOffLocation: "Private Island",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "16",
		name: "City Shuttle 303",
		type: "Bus",
		price: 25,
		availability: 0,
		pickUpLocation: "University Campus",
		dropOffLocation: "Central Library",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "17",
		name: "Executive SUV",
		type: "Car",
		price: 100,
		availability: 0,
		pickUpLocation: "Conference Center",
		dropOffLocation: "Business Park",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "18",
		name: "Suburban Line",
		type: "Train",
		price: 50,
		availability: 0,
		pickUpLocation: "Old Town Station",
		dropOffLocation: "New City Terminal",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "19",
		name: "JetStream 747",
		type: "Plane",
		price: 280,
		availability: 0,
		pickUpLocation: "Metro Airport",
		dropOffLocation: "Island Capital",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "20",
		name: "Coastal Ferry",
		type: "Boat",
		price: 160,
		availability: 0,
		pickUpLocation: "Dockside Pier",
		dropOffLocation: "Harbor Town",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "21",
		name: "Morning Coach",
		type: "Bus",
		price: 35,
		availability: 0,
		pickUpLocation: "Hotel District",
		dropOffLocation: "Mountain View",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "22",
		name: "Deluxe Minivan",
		type: "Car",
		price: 90,
		availability: 0,
		pickUpLocation: "Tech Park",
		dropOffLocation: "City Market",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "23",
		name: "Metro Express",
		type: "Train",
		price: 70,
		availability: 0,
		pickUpLocation: "Downtown Terminal",
		dropOffLocation: "Seaside Station",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "24",
		name: "Night Skyliner",
		type: "Plane",
		price: 350,
		availability: 0,
		pickUpLocation: "City Airport",
		dropOffLocation: "Desert Oasis",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
	{
		_id: "25",
		name: "Sunset Cruise",
		type: "Boat",
		price: 200,
		availability: 0,
		pickUpLocation: "Bay Harbor",
		dropOffLocation: "Sunset Island",
		pickUpTime: pickUpTimesPairs[i].pickupTime,
		dropOffTime: pickUpTimesPairs[i++].dropoffTime,
		numberOfBookings: 0,
		tourists: [],
	},
];
